api_token = 'change_me'
persistence = true
persistence_filepath = 'bot.data'
add_base_handler = true
base_handler_log_level = 'info'

[handlers]

[handlers.ping]
active = true
[handlers.ping.env]
wait_time = 2

[defaults]
tzinfo = 'utc'

[logging]
version = 1
disable_existing_loggers = true

[logging.formatters.verbose]
format = '{asctime} [{levelname}] {name} - {message}'
style = '{'

[logging.handlers.console]
class = 'logging.StreamHandler'
formatter = 'verbose'
level = 'DEBUG'

[logging.handlers.file]
class = 'logging.handlers.RotatingFileHandler'
formatter = 'verbose'
filename = 'log/telegram.log'
maxBytes = 10485760  # 10 MB
backupCount = 10

[logging.loggers.botframework]
level = 'DEBUG'
propagate = true
handlers = ['console', 'file']
