name: code-quality

on: [push]

jobs:
  isort:
    name: Check import sorting with isort
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: isort/isort-action@v1.1.0
        with:
          isort-version: '5.10.1'
          sort-paths: src
          requirements-files: requirements.txt

  black:
    name: Check code formatting with black
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with: 
          src: ./src
          version: '22.10.0'
